INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Camisa polo', 'Marca: Tommy Hilfinger', '2020-07-23' , 100 , 1 , 10);

INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Sapatilha', 'Marca: Santa Lolla', '2020-07-23' , 80 , 2 , 5);

INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Carteira', 'Marca: Le Postiche, Material : Couro', '2020-07-23' , 50 , 3 , 20);

INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Mochila', 'Marca: Osklen', '2020-07-23' , 250 , 4 , 7);

INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Shampoo', 'Marca: Ausie', '2020-07-23' , 45 , 5 , 30);

INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Regata', 'Marca: Tommy Hilfinger', '2020-07-23' , 70 , 1 , 10);

INSERT into PRODUTO (NOME, DESCRICAO, DATA_FABRICACAO, VALOR_UNITARIO, ID_CATEGORIA, QTD_ESTOQUE )
values ('Vestido', 'Marca: Dior', '2020-07-23' , 400 , 1 , 5);