INSERT into PEDIDO (DATA_PEDIDO ,ID_CLIENTE )
values(CURRENT_TIMESTAMP,1);
INSERT into PEDIDO (DATA_PEDIDO ,ID_CLIENTE )
values(CURRENT_TIMESTAMP,2);
INSERT into PEDIDO (DATA_PEDIDO ,ID_CLIENTE )
values(CURRENT_TIMESTAMP,3);
INSERT into PEDIDO (DATA_PEDIDO ,ID_CLIENTE )
values(CURRENT_TIMESTAMP,4);
INSERT into PEDIDO (DATA_PEDIDO ,ID_CLIENTE )
values(CURRENT_TIMESTAMP,5)