CREATE TABLE "PEDIDO_ITENS" (
	"ID"	INTEGER NOT NULL,
	"ID_PRODUTO"	INTEGER NOT NULL,
	"ID_PEDIDO"	INTEGER NOT NULL,
	"QUANTIDADE"	REAL NOT NULL,
	"PRECO"	REAL NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ID_PEDIDO") REFERENCES "PEDIDO"("ID"),
	FOREIGN KEY("ID_PRODUTO") REFERENCES "PRODUTO"("ID")
);