CREATE TABLE "CLIENTE" (
	"ID"	INTEGER NOT NULL,
	"NOME_COMPLETO"	TEXT NOT NULL,
	"NOME_USUARIO"	TEXT NOT NULL,
	"EMAIL"	TEXT NOT NULL UNIQUE,
	"CPF"	TEXT NOT NULL,
	"DATA_NASCIMENTO"	TEXT NOT NULL,
	"ID_ENDERECO"	INTEGER NOT NULL,
	"SENHA"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ID_ENDERECO") REFERENCES "ENDERECO"("ID")
);