INSERT INTO FUNCIONARIO_PRODUTO

(ID_FUNCIONARIO, ID_PRODUTO, ACAO, DATA_ACAO)

VALUES(1, 1, 'Cadastrou produto', CURRENT_DATE);


 

INSERT INTO FUNCIONARIO_PRODUTO

(ID_FUNCIONARIO, ID_PRODUTO, ACAO, DATA_ACAO)

VALUES(2, 2, 'Cadastrou produto', CURRENT_DATE);


 

INSERT INTO FUNCIONARIO_PRODUTO

(ID_FUNCIONARIO, ID_PRODUTO, ACAO, DATA_ACAO)

VALUES(3, 3, 'Cadastrou produto', CURRENT_DATE);


 

INSERT INTO FUNCIONARIO_PRODUTO

(ID_FUNCIONARIO, ID_PRODUTO, ACAO, DATA_ACAO)

VALUES(4, 4, 'Cadastrou produto', CURRENT_DATE);


 

INSERT INTO FUNCIONARIO_PRODUTO

(ID_FUNCIONARIO, ID_PRODUTO, ACAO, DATA_ACAO)

VALUES(5, 5, 'Cadastrou produto', CURRENT_DATE);