INSERT INTO PEDIDO_ITENS
(ID_PRODUTO, ID_PEDIDO, QUANTIDADE, PRECO)
VALUES(1, 1, 3, 95);

 

INSERT INTO PEDIDO_ITENS
(ID_PRODUTO, ID_PEDIDO, QUANTIDADE, PRECO)
VALUES(4, 1, 1, 250);

 

INSERT INTO PEDIDO_ITENS
(ID_PRODUTO, ID_PEDIDO, QUANTIDADE, PRECO)
VALUES(4, 5, 1, 250);

 

INSERT INTO PEDIDO_ITENS
(ID_PRODUTO, ID_PEDIDO, QUANTIDADE, PRECO)
VALUES(5, 2, 2, 45);

 

INSERT INTO PEDIDO_ITENS
(ID_PRODUTO, ID_PEDIDO, QUANTIDADE, PRECO)
VALUES(3, 3, 1, 50);

 

INSERT INTO PEDIDO_ITENS
(ID_PRODUTO, ID_PEDIDO, QUANTIDADE, PRECO)
VALUES(2, 4, 1, 80);