CREATE TABLE "ENDERECO" (
	"ID"	INTEGER NOT NULL,
	"RUA"	TEXT NOT NULL,
	"NUMERO"	INTEGER,
	"COMPLEMENTO"	TEXT,
	"BAIRRO"	TEXT,
	"CEP"	TEXT NOT NULL,
	"CIDADE"	TEXT NOT NULL,
	"ESTADO"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);