CREATE TABLE "PEDIDO" (
	"ID"	INTEGER NOT NULL,
	"DATA_PEDIDO"	TEXT NOT NULL,
	"ID_CLIENTE"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("ID_CLIENTE") REFERENCES "CLIENTE"("ID")
);